export const REFACTORING_HOME_URL = 'https://refactoring.fm/'
export const DREAMFORGE_DOCS_URL = 'https://github.com/OmixNet/dreamforge#readme'
export const DREAMFORGE_PRODUCT_BOARD_URL = 'https://github.com/OmixNet/dreamforge/discussions'
export const DREAMFORGE_GITHUB_DISCUSSIONS_URL = 'https://github.com/OmixNet/dreamforge/discussions'
export const DREAMFORGE_GITHUB_CONTRIBUTING_URL = 'https://github.com/OmixNet/dreamforge/blob/main/CONTRIBUTING.md'
export const DREAMFORGE_GITHUB_ISSUES_URL = 'https://github.com/OmixNet/dreamforge/issues'
export const DREAMFORGE_GITHUB_PULL_REQUESTS_URL = 'https://github.com/OmixNet/dreamforge/pulls'
